/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IMAILDeployerInterface extends ethers.utils.Interface {
  functions: {
    "BRIDGE_TOKEN()": FunctionFragment;
    "BTC()": FunctionFragment;
    "ORACLE()": FunctionFragment;
    "UNISWAP_V3_FACTORY()": FunctionFragment;
    "USDC()": FunctionFragment;
    "USDT()": FunctionFragment;
    "fees(uint256)": FunctionFragment;
    "getInterestRateModel(address)": FunctionFragment;
    "reserveFactor()": FunctionFragment;
    "riskyAsset()": FunctionFragment;
    "riskyAssetInterestRateModel()": FunctionFragment;
    "treasury()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "BRIDGE_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BTC", values?: undefined): string;
  encodeFunctionData(functionFragment: "ORACLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UNISWAP_V3_FACTORY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(functionFragment: "fees", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getInterestRateModel",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskyAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskyAssetInterestRateModel",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BRIDGE_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BTC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ORACLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UNISWAP_V3_FACTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInterestRateModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "riskyAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "riskyAssetInterestRateModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;

  events: {
    "MarketCreated(address)": EventFragment;
    "NewUniSwapFee(uint256)": EventFragment;
    "SetInterestRateModel(address,address)": EventFragment;
    "SetReserveFactor(uint256)": EventFragment;
    "SetTreasury(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MarketCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewUniSwapFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetInterestRateModel"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetReserveFactor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTreasury"): EventFragment;
}

export type MarketCreatedEvent = TypedEvent<[string] & { market: string }>;

export type NewUniSwapFeeEvent = TypedEvent<[BigNumber] & { fee: BigNumber }>;

export type SetInterestRateModelEvent = TypedEvent<
  [string, string] & { token: string; interestRateModel: string }
>;

export type SetReserveFactorEvent = TypedEvent<
  [BigNumber] & { amount: BigNumber }
>;

export type SetTreasuryEvent = TypedEvent<[string] & { account: string }>;

export class IMAILDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IMAILDeployerInterface;

  functions: {
    BRIDGE_TOKEN(overrides?: CallOverrides): Promise<[string]>;

    BTC(overrides?: CallOverrides): Promise<[string]>;

    ORACLE(overrides?: CallOverrides): Promise<[string]>;

    UNISWAP_V3_FACTORY(overrides?: CallOverrides): Promise<[string]>;

    USDC(overrides?: CallOverrides): Promise<[string]>;

    USDT(overrides?: CallOverrides): Promise<[string]>;

    fees(index: BigNumberish, overrides?: CallOverrides): Promise<[number]>;

    getInterestRateModel(
      token: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    reserveFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    riskyAsset(overrides?: CallOverrides): Promise<[string]>;

    riskyAssetInterestRateModel(overrides?: CallOverrides): Promise<[string]>;

    treasury(overrides?: CallOverrides): Promise<[string]>;
  };

  BRIDGE_TOKEN(overrides?: CallOverrides): Promise<string>;

  BTC(overrides?: CallOverrides): Promise<string>;

  ORACLE(overrides?: CallOverrides): Promise<string>;

  UNISWAP_V3_FACTORY(overrides?: CallOverrides): Promise<string>;

  USDC(overrides?: CallOverrides): Promise<string>;

  USDT(overrides?: CallOverrides): Promise<string>;

  fees(index: BigNumberish, overrides?: CallOverrides): Promise<number>;

  getInterestRateModel(
    token: string,
    overrides?: CallOverrides
  ): Promise<string>;

  reserveFactor(overrides?: CallOverrides): Promise<BigNumber>;

  riskyAsset(overrides?: CallOverrides): Promise<string>;

  riskyAssetInterestRateModel(overrides?: CallOverrides): Promise<string>;

  treasury(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    BRIDGE_TOKEN(overrides?: CallOverrides): Promise<string>;

    BTC(overrides?: CallOverrides): Promise<string>;

    ORACLE(overrides?: CallOverrides): Promise<string>;

    UNISWAP_V3_FACTORY(overrides?: CallOverrides): Promise<string>;

    USDC(overrides?: CallOverrides): Promise<string>;

    USDT(overrides?: CallOverrides): Promise<string>;

    fees(index: BigNumberish, overrides?: CallOverrides): Promise<number>;

    getInterestRateModel(
      token: string,
      overrides?: CallOverrides
    ): Promise<string>;

    reserveFactor(overrides?: CallOverrides): Promise<BigNumber>;

    riskyAsset(overrides?: CallOverrides): Promise<string>;

    riskyAssetInterestRateModel(overrides?: CallOverrides): Promise<string>;

    treasury(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "MarketCreated(address)"(
      market?: string | null
    ): TypedEventFilter<[string], { market: string }>;

    MarketCreated(
      market?: string | null
    ): TypedEventFilter<[string], { market: string }>;

    "NewUniSwapFee(uint256)"(
      fee?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { fee: BigNumber }>;

    NewUniSwapFee(
      fee?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { fee: BigNumber }>;

    "SetInterestRateModel(address,address)"(
      token?: string | null,
      interestRateModel?: string | null
    ): TypedEventFilter<
      [string, string],
      { token: string; interestRateModel: string }
    >;

    SetInterestRateModel(
      token?: string | null,
      interestRateModel?: string | null
    ): TypedEventFilter<
      [string, string],
      { token: string; interestRateModel: string }
    >;

    "SetReserveFactor(uint256)"(
      amount?: null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    SetReserveFactor(
      amount?: null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    "SetTreasury(address)"(
      account?: string | null
    ): TypedEventFilter<[string], { account: string }>;

    SetTreasury(
      account?: string | null
    ): TypedEventFilter<[string], { account: string }>;
  };

  estimateGas: {
    BRIDGE_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    BTC(overrides?: CallOverrides): Promise<BigNumber>;

    ORACLE(overrides?: CallOverrides): Promise<BigNumber>;

    UNISWAP_V3_FACTORY(overrides?: CallOverrides): Promise<BigNumber>;

    USDC(overrides?: CallOverrides): Promise<BigNumber>;

    USDT(overrides?: CallOverrides): Promise<BigNumber>;

    fees(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getInterestRateModel(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reserveFactor(overrides?: CallOverrides): Promise<BigNumber>;

    riskyAsset(overrides?: CallOverrides): Promise<BigNumber>;

    riskyAssetInterestRateModel(overrides?: CallOverrides): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BRIDGE_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BTC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ORACLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UNISWAP_V3_FACTORY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    USDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    USDT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fees(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInterestRateModel(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reserveFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    riskyAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    riskyAssetInterestRateModel(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
